---
- name: Simple Demo Playbook
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Display system information
      debug:
        msg: "Running on {{ ansible_hostname }} with {{ ansible_distribution }} {{ ansible_distribution_version }}"
    
    - name: Create a test directory in /tmp
      file:
        path: /tmp/akshay_demo_test
        state: directory
        mode: '0755'
